/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./components/sections/AboutSection.vue')['default']
    AppButton: typeof import('./components/ui/AppButton.vue')['default']
    AppContainer: typeof import('./components/ui/AppContainer.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    BurgerButton: typeof import('./components/ui/BurgerButton.vue')['default']
    CallbackModal: typeof import('./components/modals/CallbackModal.vue')['default']
    CeilingTypeModal: typeof import('./components/sections/CeilingTypeModal.vue')['default']
    CeilingTypesSection: typeof import('./components/sections/CeilingTypesSection.vue')['default']
    ContactsSection: typeof import('./components/sections/ContactsSection.vue')['default']
    FaqSection: typeof import('./components/sections/FaqSection.vue')['default']
    HeroSection: typeof import('./components/sections/HeroSection.vue')['default']
    LogoMark: typeof import('./components/ui/LogoMark.vue')['default']
    PortfolioSection: typeof import('./components/sections/PortfolioSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./components/ui/SectionTitle.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
  }
}
