/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    BurgerButton: typeof import('./components/ui/BurgerButton.vue')['default']
    LogoMark: typeof import('./components/ui/LogoMark.vue')['default']
    NavigationComponent: typeof import('./components/NavigationComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooterComponent: typeof import('./components/TheFooterComponent.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
  }
}
